--- 
jobs: 
  runs-on: ubuntu-latest
  steps: 
    - 
      uses: actions/checkout@v2
    - 
      name: "Use Node.js version 16"
      uses: actions/setup-node@v2
      with: 
        node-version: "16"
    - 
      run: "npm install"
    - 
      run: "npm run build --prefix client"
name: "ISRO MISSION LAUNCH DASHBOARD CI"
true: 
  pull_request: 
    branches: 
      - master
  push: 
    branches: 
      - master
